# Generated by Django 6.0.4 on 2026-05-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_formal_wilderness_shape_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
