# Generated by Django 6.0.4 on 2026-05-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
