# Generated by Django 6.0.4 on 2026-05-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformation',
            name='shape_style',
            field=models.CharField(choices=[('organic', 'Organic'), ('straight', 'Straight'), ('wilderness', 'Wilderness')], default='organic', max_length=16),
        ),
    ]
