# Generated by Django 6.0.4 on 2026-05-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_transformation_shape_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformation",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="thumbnails/%Y/%m/%d/"
            ),
        ),
    ]
