# Generated by Django 6.0.4 on 2026-05-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_add_thumbnail_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformation",
            name="mode",
            field=models.CharField(
                choices=[("classic", "Classic"), ("designer", "Designer")],
                default="classic",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="transformation",
            name="overlay_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="overlays/%Y/%m/%d/"
            ),
        ),
    ]
