# Generated by Django 6.0.4 on 2026-05-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_add_designer_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformation",
            name="annotated_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="annotated/%Y/%m/%d/"
            ),
        ),
    ]
